#!/bin/bash

TMP_FILE=/etc/sysconfig/iptables

# output beginning of rules
cat << EOF > $TMP_FILE
# Generated by iptables-save v1.4.7 on Mon May 26 14:13:44 2014
*filter
:INPUT ACCEPT [2072278:530643508]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1015344:313045444]
:RH-Firewall-1-INPUT - [0:0]
-A INPUT -j RH-Firewall-1-INPUT
-A FORWARD -j RH-Firewall-1-INPUT

# Allow localhost, prevent DOS attacks.
-A RH-Firewall-1-INPUT -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT
-A RH-Firewall-1-INPUT -i lo -j ACCEPT
-A RH-Firewall-1-INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# ssh
-A RH-Firewall-1-INPUT -p tcp --dport 22 -j ACCEPT

# torque
-A RH-Firewall-1-INPUT -s 130.220.208.0/20 -p tcp -m state --state NEW -m tcp --dport 15001:15004 -j ACCEPT
-A RH-Firewall-1-INPUT -s 130.220.208.0/20 -p udp -m state --state NEW -m udp --dport 15001:15004 -j ACCEPT

EOF

# write rules for each instance
for i in `/opt/dynamictorque/admin.py -w`
do
echo "# LDAP rules and NFS rules for $i" >> $TMP_FILE
echo "-A RH-Firewall-1-INPUT -s $i -p tcp -m state --state NEW -m tcp --dport 389 -j ACCEPT" >> $TMP_FILE
echo "-A RH-Firewall-1-INPUT -s $i -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT" >> $TMP_FILE
done

# output ending of rules
cat << EOF >> $TMP_FILE

# Drop multicast
-A RH-Firewall-1-INPUT -d 224.0.0.1 -j DROP
-A RH-Firewall-1-INPUT -d 224.0.0.251 -j DROP
-A RH-Firewall-1-INPUT -d 255.255.255.255 -j DROP
-A RH-Firewall-1-INPUT -m state --state INVALID -j DROP
# Turn on logging
-A RH-Firewall-1-INPUT -j LOG
# Drop everything else
-A RH-Firewall-1-INPUT -j DROP
-A INPUT -j DROP
-A FORWARD -j DROP
COMMIT
# Completed on Mon May 26 14:13:44 2014
EOF

#cp $TMP_FILE /etc/sysconfig/iptables
/etc/init.d/iptables reload

echo "mout /data on $1"
ssh-keygen -R $1
ssh -i /etc/dynamictorque/ersakey.pem -o "CheckHostIP no" -o "StrictHostKeyChecking no" ec2-user@$1 "sudo mount -t nfs4 -o rsize=32768,wsize=32768,noatime cw-vm-d0d4.sa.nectar.org.au:/data /data"