#!/bin/bash
#
# vminit  Run init script
#
# chkconfig: 2345 11 91
# description: Run init script at boot time
#
### BEGIN INIT INFO
# Provides:          vminit
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run init script
# Description:       Run init script
### END INIT INFO

PIDFILE=/var/run/vmpool/init.pid
FLAGFILE=/var/run/vmpool/initiated

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if [ -f $FLAGFILE ]; then
        echo $"VM is already initiated."
        exit 1
    fi

    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        ps $PID >/dev/null
        if [ $? -eq 0 ]; then
            PID=`cat $PIDFILE`
            echo $"vminit is already running with PID ${PID}."
            exit 1
        fi
    fi

    mkdir -p /var/run/vmpool
    echo -n $"Starting vminit:"
    nohup sh /etc/vmpool-init.sh </dev/null >/var/log/init.log 2>&1 &
    echo $! > $PIDFILE
    RETVAL=$?
    ;;
  stop)
    echo "Stopping script vminit"
    #rm -f $lockfile
    ;;
  status)
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        ps $PID >/dev/null
        if [ $? -eq 0 ]; then
            PID=`cat $PIDFILE`
            echo $"vminit is already running with PID ${PID}."
            exit 1
        fi
    fi
    
    if [ -f $FLAGFILE ]; then
        echo $"VM is already initiated."
        exit 1
    fi
    
    echo "VM hasn't been initiated."
    
    ;;
  *)
    echo "Usage: /etc/init.d/vminit {start|stop|status}"
    exit 1
    ;;
esac

exit 0
